name: aml-stock-prediction
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py311hee9e2a2_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - anyio=4.11.0=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h9408147_1
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.8.0=h9b725a8_10
  - aws-c-cal=0.8.0=h5d7ee29_2
  - aws-c-common=0.10.3=h5505292_0
  - aws-c-compression=0.3.0=h5d7ee29_2
  - aws-c-event-stream=0.5.0=h13ead76_7
  - aws-c-http=0.9.1=hf483d09_2
  - aws-c-io=0.15.2=h39f8ad8_2
  - aws-c-mqtt=0.11.0=h68a0d7e_8
  - aws-c-s3=0.7.2=h840aca7_0
  - aws-c-sdkutils=0.2.1=h5d7ee29_1
  - aws-checksums=0.2.2=h5d7ee29_1
  - aws-crt-cpp=0.29.5=h8bcca62_1
  - aws-sdk-cpp=1.11.449=h8577fd2_3
  - azure-core-cpp=1.14.0=hd50102c_0
  - azure-identity-cpp=1.10.0=hc602bab_0
  - azure-storage-blobs-cpp=12.13.0=h7585a09_1
  - azure-storage-common-cpp=12.8.0=h9ca1f76_1
  - azure-storage-files-datalake-cpp=12.12.0=hcdd55da_1
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - black=25.1.0=pyh866005b_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotli-python=1.1.0=py311hf719da1_4
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311hd10dc20_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h57a9ea7_2
  - coverage=7.11.0=py311ha9b3269_0
  - cpython=3.11.14=py311hd8ed1ab_2
  - cryptography=46.0.3=py311h054b3d0_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - datasets=2.14.4=pyhd8ed1ab_0
  - debugpy=1.8.17=py311hc58e375_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.7=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - fonttools=4.60.1=py311ha9b3269_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py311hb9fe3ed_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - isort=7.0.0=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h267d04e_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.9=py311h63e5c0c_1
  - krb5=1.21.3=h237132a_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20240722.0=cxx17_h07bc746_4
  - libarrow=18.0.0=hb943b0e_9_cpu
  - libarrow-acero=18.0.0=h286801f_9_cpu
  - libarrow-dataset=18.0.0=h286801f_9_cpu
  - libarrow-substrait=18.0.0=h6a6e5c5_9_cpu
  - libblas=3.9.0=38_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.5=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libgoogle-cloud=2.31.0=h8d8be31_0
  - libgoogle-cloud-storage=2.31.0=h7081f7f_0
  - libgrpc=1.67.1=hc70892a_0
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=pthreads_h735b822_3
  - libparquet=18.0.0=hda0ea68_9_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=5.28.2=h8f0b736_0
  - libre2-11=2024.07.02=h07bc746_2
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.21.0=h64651cc_0
  - libtiff=4.7.1=h4030677_1
  - libutf8proc=2.8.0=hc098a78_1
  - libwebp=1.6.0=hc0253d1_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.9=h4a9ca0c_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=15.0.7=h7cfbb63_0
  - lz4-c=1.9.4=hb7217d7_0
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib=3.10.7=py311ha1ab1f8_0
  - matplotlib-base=3.10.7=py311h29553df_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.1.4=pyhcf101f3_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multiprocess=0.70.15=py311heffc1b2_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy=1.18.2=py311h9408147_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.3.4=py311h8685306_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - orc=2.0.3=h121fd32_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hdb8e4fa_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - patsy=1.0.2=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.0.0=py311h890502c_0
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.1.3=py311h5bb9006_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=18.0.0=py311ha1ab1f8_2
  - pyarrow-core=18.0.0=py311he04fa90_2_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyobjc-core=12.0=py311hce6e4fa_1
  - pyobjc-framework-cocoa=12.0=py311h9049b8e_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.2=pyhd8ed1ab_0
  - pytest-cov=7.0.0=pyhcf101f3_1
  - python=3.11.14=h18782d2_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.11.14=hd8ed1ab_2
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py311hacbd903_1
  - python_abi=3.11=8_cp311
  - pytorch=2.5.1=py3.11_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311ha9b3269_0
  - pyzmq=27.1.0=py311h13abfa4_0
  - qhull=2020.2=h420ef59_5
  - re2=2024.07.02=h6589ca4_2
  - readline=8.2=h1d1bf99_2
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2025.11.3=py311h9408147_1
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.28.0=py311h71babbd_1
  - ruff=0.14.3=h382de68_1
  - scikit-learn=1.7.2=py311hc6ded6b_0
  - scipy=1.16.3=py311h2734c94_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - sentence-transformers=5.1.2=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py311h09efe57_1
  - sympy=1.14.0=pyh2585a3b_105
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_2
  - tomli=2.3.0=pyhcf101f3_0
  - torchaudio=2.5.1=py311_cpu
  - torchvision=0.20.1=py311_cpu
  - tornado=6.5.2=py311h3696347_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - tweepy=4.16.0=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=17.0.0=py311h9408147_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xxhash=0.8.3=haa4e116_0
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py311ha9b3269_0
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=h3470cca_0
  - zstandard=0.25.0=py311h5bb9006_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - alpha-vantage==3.0.0
      - curl-cffi==0.13.0
      - frozendict==2.4.6
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - hf-xet==1.2.0
      - multidict==6.7.0
      - multitasking==0.0.12
      - peewee==3.18.3
      - propcache==0.4.1
      - protobuf==6.33.0
      - safetensors==0.6.2
      - tokenizers==0.22.1
      - transformers==4.57.1
      - websockets==15.0.1
      - yfinance==0.2.66
